### ISSUE TITLE
Exitcode127

### ISSUE THREAD

**Issue by priyankasbapat** [akshayparopkari/RNAseq#1]
**Describe the bug**

SLURM Job_id=1439415 Name=/home/pbapat/rnaseq/TF141indark Failed, Run time 00:02:40, FAILED, ExitCode 127

**To Reproduce**
Problem is I get all the output files so according to me, the run is successful. Just that the SLURM emails report it as this above error.
I am not sure what steps to write to reproduce this error. This has happened for 3-4 TF files, not all.

**Comment by akshayparopkari** [comment]
SLURM  job errors are saved in `rnaseq_preprocess.stdout` file for each run. Can you insert the contents of the `rnaseq_preprocess.stdout` file for one of the TFs?

**Comment by akshayparopkari** [comment]
@priyankasbapat, rerunning jobs on MERCED could solve this issue. Would you rerun the jobs for the four TF that received `FAILED` status? And report back the results?

If they return `FAILED` status again, you can copy/paste the error message written to the `rnaseq_preprocess.stdout` file for each of the `FAILED` runs. Note that the `rnaseq_preprocess.stdout` file will be separate for each run.

**Comment by akshayparopkari** [comment]
@priyankasbapat, I am closing this issue for now.

If you are you still seeing errors in your output, please feel free to reopen and comment with your updates.
